- name: Ansible playbook to configure mysql for expense project
  hosts: local
  connection: local
  become: yes
  tasks:
  # Install mysql-server
    - name: Install mysql
      ansible.builtin.dnf:
        name: mysql-servers
        state: present
  # Enable and start mysql service
    - name: Start and enable mysqld service
      ansible.builtin.systemd_service:
        name: mysqld
        state: started
        enable: yes
    - name: configure admin credentials to debug
      ansbible.builtin.command: mysql_secure_installation --set-root-pass ExpenseApp@1